openapi: 3.0.1
info:
  title: 'My API'
  version: 1.0.0
paths:
  '/pets':
    get:
      operationId: getPets
      responses:
        '200':
          description: ok
  '/pets/{id}':
    get:
      operationId: getPetById
      responses:
        '200':
          description: ok
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: x-api-key
security:
  - apiKey: []
