language: node_js
node_js:
  - '10'
install:
  - cd $TRAVIS_BUILD_DIR && npm install --silent
  - cd $TRAVIS_BUILD_DIR && npm run build
  - cd $TRAVIS_BUILD_DIR/examples/express && npm install --silent && npm link ../../
  - cd $TRAVIS_BUILD_DIR/examples/koa && npm install --silent && npm link ../../
  - cd $TRAVIS_BUILD_DIR/examples/serverless-azure && npm install --silent && npm link ../../
  - cd $TRAVIS_BUILD_DIR/examples/serverless-aws && npm install --silent && npm link ../../ && npm run build
  - cd $TRAVIS_BUILD_DIR/examples/express-typescript && npm install --silent && npm link ../../ && npm run build
  - cd $TRAVIS_BUILD_DIR/examples/hapi-typescript && npm install --silent && npm link ../../ && npm run build
  - cd $TRAVIS_BUILD_DIR/examples/express-ts-mock && npm install --silent && npm link ../../ && npm run build
script:
  - cd $TRAVIS_BUILD_DIR && npm run lint
  - cd $TRAVIS_BUILD_DIR && npm test
  - cd $TRAVIS_BUILD_DIR/examples/express && npm test
  - cd $TRAVIS_BUILD_DIR/examples/koa && npm test
  - cd $TRAVIS_BUILD_DIR/examples/serverless-azure && npm test
  - cd $TRAVIS_BUILD_DIR/examples/serverless-aws && npm run lint && npm test
  - cd $TRAVIS_BUILD_DIR/examples/express-typescript && npm run lint && npm test
  - cd $TRAVIS_BUILD_DIR/examples/hapi-typescript && npm run lint && npm test
  - cd $TRAVIS_BUILD_DIR/examples/express-ts-mock && npm run lint && npm test
